name: weber_integration
description: A sample usage of the package
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.6.0

dependencies:
  weber: 
    path: ../weber

dev_dependencies:
  http: ^1.1.0
  lints: ^5.0.0
  test: ^1.24.0
