name: weber
description: Yet another web framework for Dart.
version: 0.0.1-alpha.1
repository: https://github.com/gbassisp/weber
homepage: https://github.com/gbassisp/weber

environment:
  sdk: ^3.5.0-152

# Add regular dependencies here.
dependencies:
  json: ^0.20.4
  lean_extensions: ^1.5.0
  macros: ^0.1.3-main.0
  meta: ^1.16.0
  shelf: ^1.0.0

dev_dependencies:
  expector: ^0.1.4
  test: ^1.24.0
  very_good_analysis: ^7.0.0
