name: weber
description: Yet another web framework for Dart.
version: 0.0.1
repository: https://github.com/gbassisp/weber

environment:
  sdk: ">=2.12.0 <4.0.0"

# Add regular dependencies here.
dependencies:
  shelf: ^1.0.0

dev_dependencies:
  expector: ^0.1.4
  test: ^1.24.0
  very_good_analysis: ^7.0.0
